<#
.SYNOPSIS
    Engram Miner — one-shot setup for Windows (Docker Desktop).

.DESCRIPTION
    Gets a miner running on Bittensor subnet 450 (testnet) without installing
    Python, Rust, or any ML toolchain on Windows — everything runs in Docker.

    Steps performed:
      1. Verify Docker Desktop is installed and running.
      2. Generate .env.miner (local embedder, matches the validator).
      3. Build the miner image.
      4. Create your wallet (coldkey + hotkey) if you don't have one.
      5. Help you register on the subnet.
      6. Start the miner and show you how to watch it.

.EXAMPLE
    # From the repo root, in PowerShell:
    powershell -ExecutionPolicy Bypass -File scripts\setup_miner.ps1

.NOTES
    Wallet keys are stored on YOUR machine at %USERPROFILE%\.bittensor and are
    never sent anywhere. Back up that folder.
#>

[CmdletBinding()]
param(
    [string]$WalletName  = "engram",
    [string]$WalletHotkey = "miner",
    [int]   $NetUid      = 450,
    [int]   $Port        = 8091
)

$ErrorActionPreference = "Stop"

# ── Pretty output ─────────────────────────────────────────────────────────────
function Info    ($m) { Write-Host "[engram] $m" -ForegroundColor Cyan }
function Success ($m) { Write-Host "[ok] $m"     -ForegroundColor Green }
function Warn    ($m) { Write-Host "[warn] $m"   -ForegroundColor Yellow }
function Fail    ($m) { Write-Host "[error] $m"  -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "  ███████╗███╗   ██╗ ██████╗ ██████╗  █████╗ ███╗   ███╗" -ForegroundColor Cyan
Write-Host "  ██╔════╝████╗  ██║██╔════╝ ██╔══██╗██╔══██╗████╗ ████║" -ForegroundColor Cyan
Write-Host "  █████╗  ██╔██╗ ██║██║  ███╗██████╔╝███████║██╔████╔██║" -ForegroundColor Cyan
Write-Host "  ██╔══╝  ██║╚██╗██║██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║" -ForegroundColor Cyan
Write-Host "  ███████╗██║ ╚████║╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║" -ForegroundColor Cyan
Write-Host "  ╚══════╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Miner Setup (Windows / Docker) · Subnet $NetUid (Testnet)"
Write-Host ""

# ── Move to repo root (this script lives in scripts\) ─────────────────────────
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot
Info "Repo root: $RepoRoot"

# ── 1. Docker checks ──────────────────────────────────────────────────────────
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Fail "Docker Desktop is not installed. Get it from https://www.docker.com/products/docker-desktop/ then re-run this script."
}
try {
    docker info *> $null
} catch {
    Fail "Docker Desktop is installed but not running. Start Docker Desktop, wait for the whale icon to settle, then re-run this script."
}
$compose = "docker compose"
try { docker compose version *> $null } catch {
    if (Get-Command docker-compose -ErrorAction SilentlyContinue) { $compose = "docker-compose" }
    else { Fail "Docker Compose not found. Update Docker Desktop to a recent version." }
}
Success "Docker is running"

# ── 2. Wallet directory (host-owned) ──────────────────────────────────────────
$WalletDir = Join-Path $env:USERPROFILE ".bittensor"
if (-not (Test-Path $WalletDir)) { New-Item -ItemType Directory -Force -Path $WalletDir | Out-Null }
$env:ENGRAM_WALLET_DIR = $WalletDir
Info "Wallet directory: $WalletDir"

# ── 3. Generate .env.miner ────────────────────────────────────────────────────
$EnvFile = Join-Path $RepoRoot ".env.miner"
if (Test-Path $EnvFile) {
    Warn ".env.miner already exists — keeping it (delete it to regenerate)"
} else {
    Info "Detecting your public IP…"
    $PublicIp = "0.0.0.0"
    try { $PublicIp = (Invoke-RestMethod -Uri "https://ifconfig.me/ip" -TimeoutSec 8).Trim() } catch {
        Warn "Could not auto-detect public IP — set EXTERNAL_IP in .env.miner manually."
    }
    @"
# Engram Miner — generated by setup_miner.ps1
WALLET_NAME=$WalletName
WALLET_HOTKEY=$WalletHotkey
SUBTENSOR_NETWORK=test
NETUID=$NetUid

MINER_PORT=$Port
EXTERNAL_IP=$PublicIp

# Local embedder — MUST match the validator (384-dim all-MiniLM). Do not change.
USE_LOCAL_EMBEDDER=true
LOCAL_EMBEDDING_MODEL=all-MiniLM-L6-v2
EMBEDDING_DIM=384

VECTOR_STORE_BACKEND=faiss
FAISS_INDEX_PATH=/app/data/miner.index

LOG_LEVEL=INFO
"@ | Set-Content -Path $EnvFile -Encoding ascii
    Success ".env.miner created (EXTERNAL_IP=$PublicIp)"
}

# ── 4. Build the miner image ──────────────────────────────────────────────────
Info "Building the miner image (first build downloads PyTorch + the model — a few minutes)…"
& cmd /c "$compose -f docker-compose.windows.yml build miner"
if ($LASTEXITCODE -ne 0) { Fail "Image build failed — scroll up for the error." }
Success "Miner image built"

# helper: run a one-off btcli command in the miner image with the wallet mounted
function Invoke-Btcli {
    param([string[]]$BtcliArgs)
    & cmd /c "$compose -f docker-compose.windows.yml run --rm -it miner btcli $($BtcliArgs -join ' ')"
}

# ── 5. Wallet creation ────────────────────────────────────────────────────────
$ColdkeyPath = Join-Path $WalletDir "wallets\$WalletName\coldkey"
$HotkeyPath  = Join-Path $WalletDir "wallets\$WalletName\hotkeys\$WalletHotkey"
if ((Test-Path $ColdkeyPath) -and (Test-Path $HotkeyPath)) {
    Success "Wallet '$WalletName' (hotkey '$WalletHotkey') already exists"
} else {
    Write-Host ""
    Warn "No wallet found at $WalletDir\wallets\$WalletName"
    $ans = Read-Host "Create a new wallet now? You'll set a password and get a mnemonic — WRITE IT DOWN. [Y/n]"
    if ($ans -eq "" -or $ans -match "^[Yy]") {
        if (-not (Test-Path $ColdkeyPath)) {
            Info "Creating coldkey…"
            Invoke-Btcli @("wallet","new_coldkey","--wallet.name",$WalletName,"--n-words","12")
        }
        Info "Creating hotkey…"
        Invoke-Btcli @("wallet","new_hotkey","--wallet.name",$WalletName,"--wallet.hotkey",$WalletHotkey,"--n-words","12")
        Success "Wallet created (saved on your machine at $WalletDir)"
    } else {
        Warn "Skipping wallet creation — the miner cannot register or earn until a wallet exists."
    }
}

# ── 6. Registration ───────────────────────────────────────────────────────────
Write-Host ""
Write-Host "══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  REGISTER ON SUBNET $NetUid (TESTNET)" -ForegroundColor Cyan
Write-Host "══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Registration needs a little testnet TAO. Get some from the faucet:"
Write-Host "    btcli wallet faucet --wallet.name $WalletName --subtensor.network test" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Then register your hotkey:"
Write-Host "    btcli subnet register --netuid $NetUid --wallet.name $WalletName --wallet.hotkey $WalletHotkey --subtensor.network test" -ForegroundColor Yellow
Write-Host ""
$reg = Read-Host "Run registration now? (needs faucet TAO already in your coldkey) [y/N]"
if ($reg -match "^[Yy]") {
    Invoke-Btcli @("subnet","register","--netuid",$NetUid,"--wallet.name",$WalletName,"--wallet.hotkey",$WalletHotkey,"--subtensor.network","test")
} else {
    Warn "Skipped registration — run the command above once you have faucet TAO, then start the miner."
}

# ── 7. Start the miner ────────────────────────────────────────────────────────
Write-Host ""
$start = Read-Host "Start the miner now? [Y/n]"
if ($start -eq "" -or $start -match "^[Yy]") {
    Info "Starting miner…"
    & cmd /c "$compose -f docker-compose.windows.yml up -d miner"
    if ($LASTEXITCODE -ne 0) { Fail "Failed to start the miner." }
    Success "Miner started"
    Write-Host ""
    Write-Host "  Watch logs :  $compose -f docker-compose.windows.yml logs -f miner" -ForegroundColor Cyan
    Write-Host "  Health     :  curl http://localhost:$Port/health" -ForegroundColor Cyan
    Write-Host "  Stop       :  $compose -f docker-compose.windows.yml down" -ForegroundColor Cyan
} else {
    Write-Host ""
    Write-Host "  Start later with:" -ForegroundColor Cyan
    Write-Host "    $compose -f docker-compose.windows.yml up -d miner" -ForegroundColor Yellow
}

Write-Host ""
Success "Done. Full guide: docs\miner-windows.md"
Write-Host ""
